
- name: Delete elk dir for sec_installation
  shell: rm -rf /data/wwwroot/elk

- name: Clone elk in Websoft9
  git:
    repo: "{{elk_git_url}}"
    dest: "/data/wwwroot/elk"

- name: Creat dir for elk
  file:
    path: "{{item}}"
    state: directory
    recurse: yes
  loop:
    - /data/wwwroot/elk/elasticsearch
    - /data/wwwroot/elk/kibana
    - /data/wwwroot/elk/logstash

- name: Rename and Run docker-compose
  shell: |
    rm -rf docker-compose.yml .env
    mv docker-compose-production.yml docker-compose.yml
    mv .env_all .env
    docker-compose up -d
    sleep 30
  args:
    chdir: /data/wwwroot/elk

- name: Check elasticsearch,kibana,logstash version
  shell: |
    sudo echo -e "elasticsearch_version: `docker exec -it elk-elasticsearch bin/elasticsearch --version | awk -F ' ' '{print $2}'`" |sudo tee -a /data/logs/install_version.txt

- name: Check elk Service
  shell: sudo docker ps
  register: check_elastic_service
  notify: check_elastic_service